
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "train_img_batch.py", line 18, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
